
spring:
  application:
    name: customer-service
# Creates the database in a file 
  datasource:
    url: jdbc:h2:file:~/customerbanking;DB_CLOSE_ON_EXIT=FALSE;
  # Generates the database *only* if it's not there yet 
  jpa:
    hibernate:
      ddl-auto: update
      # For educational purposes we will show the SQL in console 
    properties:
      hibernate:
        show_sql: true           
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true 

server:
  port: 6161

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

logging:
    file: customer.log
    level:
      root: 
      project:
          user:
            UserClient: FULL